Repository HackYourFuture-CPH/simply-name.it, pull requests merged in 2021-08, with the labels that each got.

#160 New Arrow Button Component
  src/client/components/ArrowButton/ArrowButton.component.js
  src/client/components/ArrowButton/ArrowButton.stories.js
  src/client/components/ArrowButton/ArrowButton.styles.css
Labels: storybook, group 4, frontend

#128 Add button component
  src/client/components/AddButton/AddButton.component.js
  src/client/components/AddButton/AddButton.stories.js
  src/client/components/AddButton/AddButton.styles.css
Labels: storybook, group 4, frontend

#169 Add new candidates on the Board page
  src/client/components/CandidateCard/CandidateListArray.js
  src/client/containers/BoardPage/AddCandidate.js
  src/client/containers/BoardPage/BoardPage.container.js
  src/client/containers/BoardPage/BoardPage.style.css
  src/client/containers/BoardPage/postData.js
Labels: group 4, frontend

#122 Feature/get all members endpoint
  src/server/api/controllers/members.controller.js
  src/server/api/lib/utils/http-error.js
  src/server/api/routes/boards.router.js
  src/server/api/routes/members.router.js
Labels: group 3, backend

#96 DELETE /api/users/:userid/boards/:id endpoint
  src/server/api/controllers/boards.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/boards.router.js
Labels: group 1, backend

#126 Welcome page
  src/client/App.js
  src/client/components/Auth/AuthenticatedRoute.js
  src/client/containers/WelcomePage/WelcomePage.container.js
  src/client/containers/WelcomePage/WelcomePage.stories.js
  src/client/containers/WelcomePage/WelcomePage.style.css
  src/client/containers/WelcomePage/WelcomePage.styles.css
  src/client/firebase/FirebaseContext.js
  src/client/firebase/config.js
  src/client/firebase/configure.js
  src/client/firebase/googleAuth.js
  src/client/hooks/useAuthentication.js
Labels: storybook, group 3, frontend

#179 POST Firebase token and user data
  src/client/App.js
  src/client/AppContainer.js
  src/client/components/Auth/AuthenticatedRoute.js
  src/client/components/Navigation/Header.js
  src/client/containers/ProfilePage/ProfilePage.container.js
  src/client/containers/WelcomePage/WelcomePage.container.js
  src/client/firebase/FirebaseContext.js
  src/client/firebase/UserContext.js
  src/client/firebase/configure.js
  src/client/firebase/googleAuth.js
  src/client/hooks/useAuthentication.js
Labels: backend, firebase

#176 Fix GET /users/{ID}/boards/created
  src/server/api/controllers/boards.controller.js
Labels: backend

#157 Get candidates endpoint
  src/server/api/controllers/candidates.controller.js
  src/server/api/routes/candidates.router.js
Labels: group 2, backend

#185 Style changes in Add candidate Input component: border and placeholder's color
  src/client/components/InputComponent/InputComponent.style.css
Labels: group 4, frontend

#173 Endpoint create new user
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: backend

#204 Fix user authentication logic
  src/client/components/Auth/AuthenticatedRoute.js
  src/client/firebase/FirebaseContext.js
  src/client/firebase/UserContext.js
Labels: frontend, firebase

#187 Add new candidates on the Board page
  src/client/containers/BoardPageComponents/BoardAddCandidate/AddCandidate.js
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardAddCandidate.js
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardAddCandidate.style.css
  src/client/containers/BoardPageComponents/BoardAddCandidate/PostData.js
Labels: group 4, frontend

#180 Extension of Add Candidate to the Board Endpoint
  src/server/api/controllers/candidates.controller.js
Labels: backend

#175 Add member to board POST /api/boards/boardId:/members/:memberId
  src/server/api/controllers/members.controller.js
  src/server/api/routes/members.router.js
Labels: backend

#191 Adaptation of Modal View
  src/client/components/ModalViewComponent/AdminPanel.js
  src/client/components/ModalViewComponent/MembersModal.component.js
  src/client/components/ModalViewComponent/MembersModal.stories.js
  src/client/components/ModalViewComponent/MembersModal.styles.css
  src/client/components/ModalViewComponent/MembersPanel.js
  src/client/components/ModalViewComponent/membersData.json
Labels: group 4, frontend

#207 Board add candidate component
  src/client/containers/BoardPageComponents/BoardAddCandidate/AddCandidate.js
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardAddCandidate.js
Labels: group 4, frontend

#203 CandidateList container component
  src/client/containers/BoardPageComponents/CandidateList/CandidateListPostDeadline.js
  src/client/containers/BoardPageComponents/CandidateList/CandidateListPreDeadline.js
  src/client/containers/BoardPageComponents/CandidateList/deleteCandidate.js
  src/client/containers/BoardPageComponents/CandidateList/useUpdateBallots.js
  src/client/containers/DragAndSortAdapter/OnDragEnd.js
  src/client/containers/UseHooks/useCandidates.js
  src/server/api/controllers/candidates.controller.js
Labels: group 4, frontend

#221 Board add candidate component
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardAddCandidate.js
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardAddCandidatePostDeadline.js
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardAddCandidatePreDeadline.js
Labels: group 4, frontend

#177 Dropzone component added.
  src/client/components/Dropzone/AddImageIcon.component.js
  src/client/components/Dropzone/dropzone.component.js
  src/client/components/Dropzone/dropzone.stories.js
  src/client/components/Dropzone/dropzone.styles.css
  src/client/containers/DropZone/Dropzone.container.js
Labels: frontend

#189 delete board modal created
  src/client/containers/DeleteBoardModal/DeleteBoardModal.container.js
  src/client/containers/DeleteBoardModal/DeleteBoardModal.style.css
Labels: frontend

#215 BoardHeader container for BoardPage
  src/client/components/ArrowButton/ArrowButton.styles.css
  src/client/components/Dropdown/Dropdown.css
  src/client/components/HeaderComponent/Header.component.js
  src/client/components/HeaderComponent/Header.styles.css
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardHeader.js
  src/client/containers/BoardPageComponents/BoardAddCandidate/BoardHeader.style.css
Labels: group 4, frontend

#244 userIsOwner function fix in users.controller
  src/server/api/controllers/members.controller.js
Labels: backend

#246 added votes library
  package-lock.json
  package.json
Labels: group 4, frontend

#230 Passed userId as Props and removed hard coded values from delete modal
  src/client/containers/DeleteBoardModal/DeleteBoardModal.container.js
Labels: frontend

#248 Fix: addMember function to detect role automatically
  src/server/api/controllers/members.controller.js
Labels: backend

#251 Fix: addMember page: firebase user and automatic owner addition
  src/client/App.js
  src/client/containers/AddMembersPage/AddMembersPage.container.js
  src/client/containers/CreateBoardPage/CreateBoardPage.container.js
Labels: frontend

#252 added seeds in production
  src/server/seeds/production/01_users.js
  src/server/seeds/production/02_boards.js
  src/server/seeds/production/03_members.js
  src/server/seeds/production/04_candidates.js
  src/server/seeds/production/05_ballots.js
Labels: deployment

#238 Elasticsearch implementation
  package.json
  src/server/api/controllers/users.controller.js
  src/server/api/lib/utils/syncES.js
  src/server/api/routes/users.router.js
  src/server/config/elastic.js
Labels: backend, elasticsearch

#233 error handler for deleteCandidate function
  src/client/containers/BoardPageComponents/CandidateList/CandidateListPreDeadline.js
  src/client/containers/BoardPageComponents/CandidateList/deleteCandidate.js
Labels: frontend
